adapter_list:
  - left_arm
  - right_arm
  
left_arm:
    joint_state_topic: "left_arm/joint_control/get_state"
    joint_command_topic: "left_arm/joint_control/move"
    joint_name_prefix: "left_"
right_arm:
    joint_state_topic: "right_arm/joint_control/get_state"
    joint_command_topic: "right_arm/joint_control/move"
    joint_name_prefix: "right_"