joint_limits:
  left_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 0.314159265359
    has_acceleration_limits: true
    max_acceleration: 0.0628318530718
  left_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518
  right_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: true
    max_acceleration: 0.0383972435438
  right_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518
  right_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: true
    max_acceleration: 0.0383972435438
  left_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 0.314159265359
    has_acceleration_limits: true
    max_acceleration: 0.0628318530718
  right_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518
  right_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518
  left_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518
  right_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 0.314159265359
    has_acceleration_limits: true
    max_acceleration: 0.0628318530718
  right_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 0.314159265359
    has_acceleration_limits: true
    max_acceleration: 0.0628318530718
  left_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: true
    max_acceleration: 0.0383972435438
  left_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: true
    max_acceleration: 0.0383972435438
  left_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.226892802759
    has_acceleration_limits: true
    max_acceleration: 0.0453785605518